### ISSUE TITLE
Автоматический деплоймент

### ISSUE THREAD

**Issue by umputun** [umputun/rt-bot#130]
- Добавить на bot.radio-t.com API для этого дела - `GET /deploy`. С http auth.
- Поменять загрузку всех внешнких ботов с одноразовой (во времq старта), на периодическую (дергать /list каждую минуту, и догружать/перегружать если появился/исчез бот)
- Добавить вызов API для deplpy со стороны CI

**Comment by selevit** [comment]
> GET /deploy

Наверно все-таки POST кошернее.

**Comment by selevit** [comment]
Также, вместе с этим изменением желательно сделать ветку develop и деплоить ее в тестовый чат.

**Comment by umputun** [comment]
для этого тебе надо строить image с тэгами. `:latest` для мастера, `:develop` для девелоп

**Comment by selevit** [comment]
Это не проблема. Только тебе нужно два сервера :)

**Comment by selevit** [comment]
Я как-то об этом не подумал сначала. Наверно пока лишнее.

**Comment by umputun** [comment]
добавил сервис на `https://bot.radio-t.com:1443/deploy`

его пришлось делать отдельным и независимым от того, что он деплоит и он запускается через `docker-compose-deploy.yml` 

можешь попробовать добавить это дело в CI. Только имей ввиду - он не даст делать несколько деплоев одновременно. Пока бежит один запрос, друой будет падать на timeout

**Comment by selevit** [comment]
Как я понимаю, запрос будет висеть, пока деплой не кончится?

**Comment by umputun** [comment]
да. если это долго делать то трэвис упадет на timeout

**Comment by selevit** [comment]
Пока можно ограничить лимит одновременных сборок в мастере (на уровне travis).

**Comment by umputun** [comment]
я добавил DEPLOY_USER и DEPLOY_PASSWD в travis

**Comment by umputun** [comment]
хмм, wtf? 

`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

это оно так на `/usr/bin/docker images --no-trunc | grep none | awk "{print \$3}" | xargs /usr/bin/docker rmi` При этом там есть `DOCKER_HOST` и compose его видит. 

Если есть идеи - дайте знать.

**Comment by selevit** [comment]
Так ты ж его в докере запускаешь?
Надо пробросить `/var/run/docker.sock:/var/run/docker.sock` как volume.

**Comment by selevit** [comment]
Хм, оно ж вроде и есть у тебя.

**Comment by umputun** [comment]
конечно есть, compose без этого бы ругался тоже.

**Comment by selevit** [comment]
> unix://var/run/docker.sock

Может быть `unix:///var/run/docker.sock`

**Comment by selevit** [comment]
Нельзя возвращать 503 Service Unavailable, если деплой уже идет?

**Comment by umputun** [comment]
хмм, а зачем? пусть ждет своего часа. или вызывай с timeout своим курлом или чем оно там дергается

**Comment by umputun** [comment]
и таки, да `unix:///var/run/docker.sock`, thx

**Comment by selevit** [comment]
Да, про 503 я уже передумал.
Ну и да, когда курлу говоришь перенаправлять поток, то он в stderr выводит статистику по выполнению запроса (изменяется время, количество переданных байт).
Поэтому билд будет выполняться и не убьется трэвисом.

**Comment by selevit** [comment]
Значит композу пофиг на ENV DOCKER_HOST, если он не ругался.

**Comment by umputun** [comment]
маловероятно. Скорее всего у него хватает ума на default в такой ситуавии
