### ISSUE TITLE
Нет, эти сумашедшие гифки не наш путь

### ISSUE THREAD

**Issue by umputun** [umputun/rt-bot#137]
Я таки прибью бота который крутит эти дикие гифки и добавлю рекомендацию каких ботов лучше не делать. Если есть идеи по списку нежелательнх видов ботов, то оставляйте здесь, подумаем.

**Comment by aohorodnyk** [comment]
![screenshot_21](https://cloud.githubusercontent.com/assets/566026/20601299/9c1a4cac-b260-11e6-8a93-6ab1d2a5c44b.png)
Я также предлагаю не принимать ботов, которые зависят на внешние платные сервисы с ограниченым бесплатным тарифом.

**Comment by umputun** [comment]
запретил. Буду стараться не принимать подобное.
