### ISSUE TITLE
Бесполезный тест в 5minphp-bot

### ISSUE THREAD

**Issue by budnik** [umputun/rt-bot#144]
Регексп из [теста](https://github.com/umputun/rt-bot/blob/master/5minphp-bot/bot-spec.yml#L14) `/^.*(PHP)?(php)?.*$/` матчит любую строку.
В таком тесте нет особо смысла, нужно его удалить или заменить регексп на `/.*/`

**Comment by budnik** [comment]
cc @selevit

**Comment by selevit** [comment]
@umputun , закрой этот тикет тоже.
