### ISSUE TITLE
money_bot

### ISSUE THREAD

**Issue by exelban** [umputun/rt-bot#153]
Есть еще идея добавить курсы валют. Например в чате можно будет вписать USD_EUR и получить курс долара к евро.
Есть ли смысл делать это?

**Comment by selevit** [comment]
Если уж добавлять, то в формате "500 долларов в рублях", а не машиночитаемом.

**Comment by exelban** [comment]
Ну сейчас так есть, если впишешь 500 долларов, то ответить сколько это в евро, рублять, гривнях.

**Comment by alehano** [comment]
Бесплатный API по валютам к рублю http://www.cbr.ru/scripts/XML_daily.asp
И кешировать желательно.

**Comment by ssgreg** [comment]
https://github.com/umputun/rt-bot/tree/master/xrates-bot

**Comment by umputun** [comment]
@ssgreg это какое-то тонкое издевательство ? эта штука тянет около гига в базовом образе а потом собирается ... вечно.
