### ISSUE TITLE
падают тесты, нужна помощь

### ISSUE THREAD

**Issue by Rabinzon** [umputun/rt-bot#164]
Тесты xrates, и search бота фейлятся. 
Судя по коммитам xrates был удален, но папка с сарцами осталась. Самовольно удалять не осмелился. 
почему валится search-bot, пока не разобрался.
https://travis-ci.org/umputun/rt-bot/builds/186535295#L5267 

пр: https://github.com/umputun/rt-bot/pull/163

**Comment by exelban** [comment]
xrates уже удален, а вот проблема с search-bot актуальная.

**Comment by selevit** [comment]
https://github.com/umputun/rt-bot/pull/168
