### ISSUE TITLE
bot-4-bots - таблицы не отображаются в ответе

### ISSUE THREAD

**Issue by khaale** [umputun/rt-bot#176]
Ответ бота не рендерится в таблицу, а отображается в исходном виде (хотя ссылки при этом форматируются нормально):
```
Bot Name | Created On ↓ | Created By | Last Changed On | Last Changed By
---------|-------------------|------------|-----------------|----------------
bot-4-bots|12/28/2016|khaale|01/06/2017|khaale|
docker-bot|12/26/2016|Vitaly Pryakhin|01/01/2017|Vitaly Pryakhin|
random-bot|12/24/2016|Rabinzon|12/29/2016|Rabinzon|
money_bot|12/09/2016|exelban|12/25/2016|exelban|
```
вместо

Bot Name | Created On ↓ | Created By | Last Changed On | Last Changed By
---------|-------------------|------------|-----------------|----------------
bot-4-bots|12/28/2016|khaale|01/06/2017|khaale|
docker-bot|12/26/2016|Vitaly Pryakhin|01/01/2017|Vitaly Pryakhin|
random-bot|12/24/2016|Rabinzon|12/29/2016|Rabinzon|
money_bot|12/09/2016|exelban|12/25/2016|exelban|

Можно ли посмотреть на дамп сообщения, которое radio-t бот постит в gitter от имени бота? Возможно, дело в каком-нибудь дополнительном форматировании.

**Comment by umputun** [comment]
подозреваю, что там у тебя \n прямо в json? должно быть \\n. это где-то описано.

вообще вcе, что оно делает для сообщения, это вот это:

```go
respMD := fmt.Sprintf("**%s 💬**  %s", respData.Bot, strings.Replace(respData.Text, "\\n", "\n  ", -1))
```

**Comment by khaale** [comment]
`\\n` я уже поправил, а вот эта штука `**%s 💬**` почему-то сбивает форматирование таблиц.
Воспроизводится даже если вручную отправлять сообщения в чат:

```
**%s 💬**
Bot Name | Created On ↓ | Created By | Last Changed On | Last Changed By
---------|-------------------|------------|-----------------|----------------
bot-4-bots|12/28/2016|khaale|01/06/2017|khaale|
```

Без `**%s 💬**` - все нормально.

**Comment by khaale** [comment]
Кажется, что исправляется добавлением лишнего переноса строки в начале: `\\n\\n ...`

**Comment by khaale** [comment]
Fixed in #177
