### ISSUE TITLE
run_local.sh - ssl сертификаты всегда создаются заново

### ISSUE THREAD

**Issue by khaale** [umputun/rt-bot#178]
В скрипте ./run_local.sh условие в if-е выглядит странно, оно проверяет либо отсутствие SSL_KEY файла, либо наличие SSL_CERT: `if [ ! -f "$SSL_KEYS_DIR/$SSL_KEY" ] ||  [ -f "$SSL_KEYS_DIR/$SSL_CERT" ]`.
В результате сертификаты всегда пересоздаются.

Тут есть какие-то глубокие мотивы, или просто забыли **!** во второй части условия?

**Comment by selevit** [comment]
Это опечатка, поправил, спасибо.

**Comment by selevit** [comment]
Можно закрыть issue
