### ISSUE TITLE
Тестовый сетап

### ISSUE THREAD

**Issue by umputun** [umputun/rt-bot#39]
Я подниму бота на gitter канале `umputun/test` чтоб все авторы могли поиграться и потестирвоать это хозяйство в реальной жизни

**Comment by bessarabov** [comment]
Если я правильно нашел, то ссылка на канал — https://gitter.im/umputun/test

**Comment by umputun** [comment]
ваши боты живы на https://gitter.im/umputun/test
вы пробуйте, там почти все криво работают.

@gangstaJS - если не поменяешь источник, то я твой бот прибью
