### ISSUE TITLE
чиним кошмар у ужас /info

### ISSUE THREAD

**Issue by umputun** [umputun/rt-bot#60]
Вот вам правила для `/info`:
1. **не включать свой твитер** - он раскрывается в гиттере
1. не использовать болд и любое другое оформление нигде вообще в /info ответе.

Все остальное форматирование для вас будет сделано.

**Comment by umputun** [comment]
вы можете включить свой твитер в md, такое гиттер не раскроет

`[@umputun](https://twitter.com/umputun)`

**Comment by selevit** [comment]
Я бы еще добавил правило использовать кавычки-елочки и длинные тире вместо дефисов.
Чтобы вообще смотрелось цивильно.
Может быть полезен этот инструмент: http://typograf.ru/.

**Comment by pqr** [comment]
@umputun, я попробовал сделать ссылку на твиттер в маркдауне по рецепту, но на деле при клике по @nickname открывается https://github.com/nickname (обнаружил в приложении Gitter под iOS, на десктопе не успел проверить).

Думаю это Gitter такой хитрый, что слова начинающиеся с @ делает ссылками на github аккаунты.

Нужен другой рецепт, как минимум, не использовать @

**Comment by umputun** [comment]
на десктопе идет в твитер

**Comment by alehano** [comment]
А переносы строк в /info можно?

**Comment by umputun** [comment]
да, экранированые как и в других местах
