### ISSUE TITLE
anek-bot - надо br обрабатывать, однако

### ISSUE THREAD

**Issue by umputun** [umputun/rt-bot#61]
![8q1fm-201611-14111908-4zqzz](https://cloud.githubusercontent.com/assets/535880/20274970/440bf7f6-aa5c-11e6-95ed-c7938416fcb5.png)

@terbooter

**Comment by terbooter** [comment]
@umputun , <br> заменены на переносы строки
![image](https://cloud.githubusercontent.com/assets/429392/20337810/5da4342e-abe4-11e6-84b5-972433e54687.png)
