### ISSUE TITLE
Боты в действии

### ISSUE THREAD

**Issue by valeriyvan** [umputun/rt-bot#79]
Как увидеть существующих ботов в действии?
Зашел в чятик https://chat.radio-t.com или https://gitter.im/radio-t/chat, написал /karma.
Карма бот должен на это что-то ответить? Ничего не происходит.
Или пишу Гвидо, гвидо-бот в ответ должен запостить картинку. Нифига не происходит.
Чего я не понимаю?

**Comment by umputun** [comment]
последняя строка в README.md прямо и авно товечает на этот вопрос
