### ISSUE TITLE
Grabpage-bot отвечает 502 Bad Gateway

### ISSUE THREAD

**Issue by denisvolokh** [umputun/rt-bot#82]
Привет,

Grabpage-bot отвечает 502 на тестовый запрос

`curl --request POST \
  --url https://bot.radio-t.com/api/grabpage-bot/event \
  --header 'content-type: application/json' \
  --data '{
	"text" : "Bla bla bla www.mail.ru"
}'`

**Comment by umputun** [comment]
ну так, это … чини? ты, кстати, почему-то не добавил бот в композ, я это тебе добавил. Ну а почему не отвечает - откуда мне знать. Прокси ты сам прописывал, оно на твой контейнер все посылает.

**Comment by umputun** [comment]
`aiohttp.web.run_app(web_app, host="127.0.0.1", port=8080)` это нормально?

**Comment by denisvolokh** [comment]
Спасибо за композ. Уже нашел в чем дело, добавлю /info и фикс для этого бага.
