### ISSUE TITLE
Надо бы в brackets-bot добавить исключения для всяких смайлов

### ISSUE THREAD

**Issue by selevit** [umputun/rt-bot#98]
Когда пишешь в чат смайлы а-ля `:(`, то brackets-bot ругается на незакрытые скобки.
Хорошо бы добавить исключение для таких вещей.

**Comment by holms** [comment]
Товарищи либо чините, либо нахрен вырибуте, даже стандартные смайлы не понимает в гиттере которые там в emoticons конвертируются
